name: hubmap
channels:
  - conda-forge
  - anaconda
  - pytorch
dependencies:
  - python=3.7
  - pillow=7.2.0
  - pytz=2020.5
  - pytorch=1.7.0
  - cudatoolkit=10.1
  - torchvision
  - tifffile
  - pip
  - pip:
      - opencv-python
